// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/nuea/backend-golang-test/cmd/http/internal/handler"
	auth2 "github.com/nuea/backend-golang-test/cmd/http/internal/handler/auth"
	"github.com/nuea/backend-golang-test/cmd/http/internal/handler/user"
	"github.com/nuea/backend-golang-test/cmd/http/internal/server"
	"github.com/nuea/backend-golang-test/internal/client"
	"github.com/nuea/backend-golang-test/internal/client/backendgolangtest"
	"github.com/nuea/backend-golang-test/internal/client/mongodb"
	"github.com/nuea/backend-golang-test/internal/config"
	"github.com/nuea/backend-golang-test/internal/di"
	"github.com/nuea/backend-golang-test/internal/middleware"
	auth3 "github.com/nuea/backend-golang-test/internal/middleware/auth"
	"github.com/nuea/backend-golang-test/internal/service"
	"github.com/nuea/backend-golang-test/internal/service/auth"
)

// Injectors from di.go:

func InitContainer() (*Container, func(), error) {
	appConfig := config.ProvideCofig()
	mongoDB, cleanup, err := mongodb.ProvideMongoDBClient(appConfig)
	if err != nil {
		return nil, nil, err
	}
	apiClient := backendgolangtest.ProvideBackendGolangTestServiceGRPC(appConfig)
	userServiceClient := backendgolangtest.ProvideUserServiceClient(apiClient)
	authServiceClient := backendgolangtest.ProvideAuthServiceClient(apiClient)
	backendGolangTestGRPCService := &backendgolangtest.BackendGolangTestGRPCService{
		UserServiceClient: userServiceClient,
		AuthServiceClient: authServiceClient,
	}
	clients := &client.Clients{
		MongoDB:                      mongoDB,
		BackendGolangTestGRPCService: backendGolangTestGRPCService,
	}
	authService := auth.ProvideAuthenticationService(appConfig, clients)
	serviceService := &service.Service{
		AuthService: authService,
	}
	authHandler := auth2.ProvideUserHandler(serviceService)
	userHandler := user.ProvideUserHandler(clients)
	handlers := &handler.Handlers{
		AuthHandler: authHandler,
		UserHandler: userHandler,
	}
	authMiddleware := auth3.ProvideAuthMiddleware(serviceService)
	middlewareMiddleware := &middleware.Middleware{
		Auth: authMiddleware,
	}
	httpServer := server.ProvideHTTPServer(appConfig, handlers, clients, middlewareMiddleware)
	container := &Container{
		server: httpServer,
	}
	return container, func() {
		cleanup()
	}, nil
}

// di.go:

var MainSet = wire.NewSet(di.InternalSet, ProviderSet, handler.HandlerSet, wire.Struct(new(Container), "*"))
