// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/nuea/backend-golang-test/cmd/grpc/internal/handler"
	"github.com/nuea/backend-golang-test/cmd/grpc/internal/handler/user"
	"github.com/nuea/backend-golang-test/cmd/grpc/internal/server"
	"github.com/nuea/backend-golang-test/internal/config"
	"github.com/nuea/backend-golang-test/internal/di"
)

// Injectors from di.go:

func InitContainer() (*Container, func(), error) {
	appConfig := config.ProvideCofig()
	userServiceServer, err := user.ProvideUserGRPCService()
	if err != nil {
		return nil, nil, err
	}
	grpcServices := &handler.GrpcServices{
		UserServiceServer: userServiceServer,
	}
	grpcServer := server.ProvideGRPCServer(appConfig, grpcServices)
	container := &Container{
		server: grpcServer,
	}
	return container, func() {
	}, nil
}

// di.go:

var MainSet = wire.NewSet(di.InternalSet, ProviderSet, handler.HandlerSet, wire.Struct(new(Container), "*"))
